platform :ios, '7.0'
pod 'PureLayout'
pod 'CocoaHTTPServer'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'WYPopoverController' ,:git => 'https://github.com/sammcewan/WYPopoverController.git'
pod 'PKYStepper', '~> 0.0.1'
